### ISSUE TITLE
ไม่สามารถ เลือก menu ของแขวง/เขต (Auto complete) ที่ขึ้นมาได้

### ISSUE THREAD

**Issue by gookgagaa** [tsctao/vue-thai-address-input#1]
สวัสดีค่ะ ก่อนอื่นขอขอบคุณสำหรับ component ดีๆที่สร้างขึ้นมานะคะ
แต่พอดีได้ลองเอาไปใช้ แล้วพบว่า ไม่สามารถเลือก menu ของแขวง/เขต (Auto complete) ที่ขึ้นมาได้ค่ะ
ได้ลองบน browser google chrome Version 62.0.3202.75 (Official Build) (64-bit).

**Comment by tsctao** [comment]
ขอตัวอย่างโค้ดกับ error ใน console (ถ้ามี) หน่อยครับ

**Comment by gookgagaa** [comment]
ดูใน console ไม่เจอ error ค่ะ ตอนนี้พอดีไม่ได้เอาคอมที่มี code มา แต่ว่าลองที่ DEMO page ก็เจอปัญหาเดียวกันนะคะ (https://tsctao.github.io/vue-thai-address-input/)

ได้อัด VDO ไว้ ตอนลองเล่นค่ะ เผื่อทำให้เห็นภาพมากขึ้น (อยู่ใน Zip file)
[VDO - Vue thai address input selected issue.zip](https://github.com/tsctao/vue-thai-address-input/files/1433402/VDO.-.Vue.thai.address.input.selected.issue.zip)

**Comment by tsctao** [comment]
รู้สึกจะมีปัญหากับ Google Chrome บน Windows เพราะลองใช้บน browser อื่น หรือบน macOS ก็ใช้ได้

ตอนนี้ผมไม่มีเครื่อง Windows ที่ใช้ dev อ่ะครับ ลองเอา source ไปแก้เลยก็ได้ครับ ไม่งั้นก็คงต้องรอก่อนนะครับ

**Comment by gookgagaa** [comment]
ลองเปลี่ยน จาก event on click ไปเป็น mousedown ตรงส่วนของ  menu div suggestion-list-item แล้วทำงานได้บน Google Chrome on Windows ค่ะ :)

**Comment by tsctao** [comment]
เดี๋ยวดูให้อีกทีนะครับ พอได้เบาะแสบ้างแล้ว ถ้าเปลี่ยนเป็น mousedown ถ้าเข้าใจไม่ผิดจะกดบนมือถือไม่ได้นะครับ

**Comment by tsctao** [comment]
แก้ให้แล้วนะครับ
